allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
  sharp: true
  unrs-resolver: true

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "astro"
  - "@astrojs/**"
  - "eslint"
  - "@eslint/*"
  - "vite"
  - "@typescript-eslint/*"
  - fast-uri@3.1.4

catalog:
  eslint: ^10.5.0

overrides:
  eslint: "catalog:"

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 525600
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
