allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
  sharp: true
  unrs-resolver: true

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "astro"
  - "@astrojs/**"
  - "eslint"
  - "@eslint/*"
  - "vite"

overrides:
  esbuild: ">=0.28.1"
  "brace-expansion@5.0.5": ">=5.0.6"
  yaml: ">=2.8.3"

trustPolicy: no-downgrade
