allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
  sharp: true
  unrs-resolver: true

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "astro"
  - "@astrojs/**"
  - "eslint"
  - "@eslint/*"
  - "vite"
  - "@typescript-eslint/*"

catalog:
  eslint: ^10.7.0

overrides:
  eslint: "catalog:"
  devalue: ">=5.9.1"

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 525600
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
